{
  "models": [
    {
      "name": "Llama-3-8B-Instruct",
      "provider": "huggingface",
      "reference": "meta-llama/Meta-Llama-3-8B-Instruct",
      "task": "text-generation",
      "min_vram_gb": 16,
      "quantization": "bitsandbytes-4bit",
      "notes": "Solid general-purpose instruction-tuned LLM."
    },
    {
      "name": "Mistral-7B-Instruct",
      "provider": "huggingface",
      "reference": "mistralai/Mistral-7B-Instruct-v0.3",
      "task": "text-generation",
      "min_vram_gb": 12,
      "quantization": "bitsandbytes-4bit",
      "notes": "Lightweight, fast to fine-tune on consumer GPUs."
    },
    {
      "name": "SDXL-Base",
      "provider": "huggingface",
      "reference": "stabilityai/stable-diffusion-xl-base-1.0",
      "task": "image-generation",
      "min_vram_gb": 16,
      "quantization": null,
      "notes": "High-quality latent diffusion for images."
    }
  ]
}